name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start MySQL service
        run: sudo systemctl start mysql.service

      - name: Create ESTORE database
        run: |
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS ESTORE;"

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Start backend service
        run: |
          nohup java -jar target/Products-0.0.1-SNAPSHOT.jar & sleep 30

      - name: Run Tests
        run: mvn test -Dtest.port=8081

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USER}}
          password: ${{secrets.EMAIL_PASS}}
          subject: GitHub Actions job result for ${{github.repository}}
          body: The job ${{github.job}} in workflow ${{github.workflow}} of ${{github.repository}} has completed. See attached test reports.
          to: ntumyredeemer@gmail.com
          from: GitHub Actions
          attachments: target/surefire-reports/*.xml
